/* UI chrome strings — English (the fallback locale).
   Loaded as a plain global so the site works on file:// with no fetch/CORS.
   To add a language, copy this file to strings.<code>.js and translate the
   right-hand sides, then register the locale in assets/shared.js (LOCALES). */
(function () {
  var S = (window.LA_STRINGS = window.LA_STRINGS || {});
  S.en = {
    "site.brand": "Linear algebra, visually",
    "site.footer": "Visual notes for linear algebra, built with plain HTML, Canvas2D and KaTeX.",

    "nav.home": "Home",
    "nav.2d": "2D",
    "nav.3d": "3D",
    "nav.glossary": "Glossary",
    "nav.notation": "Notation",
    "nav.notes": "Notes",
    "nav.theme": "Toggle light or dark theme",
    "nav.language": "Language",

    "glossary.title": "Glossary",
    "glossary.intro": "Cross-linked definitions. Every term cites where it is developed in two standard texts, plus a video when one explains it well. Search, or filter by tag.",
    "glossary.search": "Search terms, symbols, definitions…",
    "glossary.allTags": "All",
    "glossary.formal": "Formal",
    "glossary.seeAlso": "See also",
    "glossary.sources": "Sources",
    "glossary.count": "{n} of {total} terms",
    "glossary.none": "No terms match.",
    "glossary.copyLink": "Copy link to this term",

    "notation.title": "Notation & conventions",
    "notation.intro": "Every symbol used across these notes, what to read it as, and the conventions this site commits to.",
    "notation.colSymbol": "Symbol",
    "notation.colName": "Name",
    "notation.colMeaning": "Meaning",
    "notation.colRead": "Read as",

    "notes.title": "Notes",
    "notes.intro": "Longer-form notes. Hover any underlined term for its definition.",
    "notes.loading": "Loading…",
    "notes.missing": "Note not found.",
    "notes.index": "All notes",
    "notes.serveHint": "Notes are fetched at runtime, so this page needs to be served over http(s) (GitHub Pages or a local server), not opened as a file://.",

    "cite.free": "free",
    "cite.openAccess": "open access, free PDF",
    "cite.paid": "paid",
    "cite.video": "video",

    "home.eyebrow": "Visual notes",
    "home.title": "Linear algebra you can see",
    "home.lede": "Durable, visual notes for linear algebra: the thing to reach for when you've forgotten what a determinant <em>means</em>, not just how to compute one. Definitions and notation are the spine; the interactive visualisations hang off them. Every definition cites two standard texts and, where one explains it best, a video.",
    "home.2d.kicker": "Interactive",
    "home.2d.title": "2D transformations",
    "home.2d.desc": "Type a 2×2 matrix and watch the grid bend. The shaded unit square's area is the determinant.",
    "home.3d.kicker": "Interactive",
    "home.3d.title": "3D transformations",
    "home.3d.desc": "Orbit a 3×3 transformation. The unit cube's signed volume is the determinant.",
    "home.glossary.kicker": "Reference",
    "home.glossary.title": "Glossary",
    "home.glossary.desc": "Cross-linked, fully-cited definitions. Search or filter by tag; follow 'see also' chips between ideas.",
    "home.notation.kicker": "Reference",
    "home.notation.title": "Notation",
    "home.notation.desc": "Every symbol used here, what to read it as, and the conventions this site commits to.",
    "home.notes.kicker": "Notes",
    "home.notes.title": "Notes",
    "home.notes.desc": "Longer-form notes with hover-card definitions on any underlined term.",

    "viz.tab.transform": "Transform",
    "viz.tab.inverse": "Inverse",
    "viz.tab.compose": "Compose",
    "viz.inv.sub": "The inverse A⁻¹ undoes A. Apply A, then A⁻¹, and space returns to where it began.",
    "viz.inv.applyUndo": "Apply A, then undo",
    "viz.inv.label": "Inverse A⁻¹",
    "viz.inv.none": "det(A) = 0, so A collapses space to a lower dimension. There is no inverse: a collapse cannot be undone.",
    "viz.inv.stageApply": "Applying A",
    "viz.inv.stageUndo": "Undoing with A⁻¹",
    "viz.shapes.label": "Drop a shape (drag it in the space)",
    "viz.shapes.clear": "Clear shapes",
    "viz.inv.title": "The inverse undoes A",
    "viz.inv.matrixA": "Matrix A",
    "viz.shapes.point": "Place a point",
    "viz.shapes.vector": "Place a vector",
    "viz.shapes.square": "Place a unit square",
    "viz.shapes.circle": "Place a circle",
    "viz.shapes.triangle": "Place a triangle",
    "viz.shapes.fglyph": "Place an F glyph",

    "viz.presets": "Presets",
    "viz.readout": "Readout",
    "viz.animate": "Animate from identity",
    "viz.reset": "Reset",
    "viz.det": "Determinant",
    "viz.orient": "Orientation",
    "viz.orient.preserved": "preserved",
    "viz.orient.flipped": "flipped",
    "viz.orient.collapsed": "collapsed (singular)",
    "viz.iGoesTo": "î goes to",
    "viz.jGoesTo": "ĵ goes to",
    "viz.kGoesTo": "k̂ goes to",

    "viz2d.title": "Transformation matrix",
    "viz2d.sub": "Each <em>column</em> says where a basis vector lands. The grid bends to follow. See <a href=\"glossary.html#matrix\">matrix</a> &amp; <a href=\"glossary.html#determinant\">determinant</a>.",
    "viz2d.iLands": "î lands here",
    "viz2d.jLands": "ĵ lands here",
    "viz2d.areaScale": "Area scale",
    "viz2d.hint": "The shaded patch is the image of the unit square. Its signed area equals the <a href=\"glossary.html#determinant\">determinant</a>: negative means space got flipped, zero means it collapsed onto a line and the matrix is <a href=\"glossary.html#singular\">singular</a>.",
    "viz2d.stageHint": "Each column of the matrix is where a basis vector lands.",
    "viz2d.p.rot90": "Rotate 90°",
    "viz2d.p.rot45": "Rotate 45°",
    "viz2d.p.shearX": "Shear x",
    "viz2d.p.shearY": "Shear y",
    "viz2d.p.scale2": "Scale 2×",
    "viz2d.p.flipX": "Flip x",
    "viz2d.p.flipY": "Flip y",
    "viz2d.p.collapse": "Collapse",

    "viz3d.title": "3×3 transformation",
    "viz3d.sub": "Each <em>column</em> is where a basis vector lands. The <a href=\"glossary.html#determinant\">determinant</a> is now a signed <a href=\"glossary.html#area-volume\">volume</a>.",
    "viz3d.volScale": "Volume scale",
    "viz3d.hint": "The shaded box is the image of the unit cube; its signed volume is the determinant. Zero volume means space was squashed flat (<a href=\"glossary.html#singular\">singular</a>). Negative means the handedness flipped.",
    "viz3d.stageHint": "Drag to orbit · scroll to zoom",
    "viz3d.p.rotZ90": "Rotate z 90°",
    "viz3d.p.rotY45": "Rotate y 45°",
    "viz3d.p.shearZX": "Shear (z→x)",
    "viz3d.p.scale15": "Scale 1.5×",
    "viz3d.p.reflectZ": "Reflect z",
    "viz3d.p.squash": "Squash to plane",

    "nav.matmul": "Multiply",
    "nav.concepts": "Concepts",
    "keyideas.label": "Key ideas to remember",
    "glossary.theorems": "Theorems",

    "concepts.title": "Concepts",
    "concepts.intro": "Visual explainers for the ideas the transformations rest on. Each one is interactive and cited.",
    "concepts.kicker": "Concept",
    "concepts.span.title": "Span",
    "concepts.span.desc": "Drag vectors and watch what they span: a line, a plane, or all of space, and the moment they become dependent.",
    "concepts.subspaces.title": "Rank, column & null space",
    "concepts.subspaces.desc": "See what survives a map and what collapses: column space, null space, rank, and why det = 0 means singular.",
    "concepts.dimensions.title": "Maps between dimensions",
    "concepts.dimensions.desc": "Non-square matrices send n-dimensional space to m dimensions. Watch 3D squash to a plane, or the plane lift into space.",
    "concepts.dot.title": "Dot product",
    "concepts.dot.desc": "Drag two vectors to see the dot product as length times length times the cosine of the angle between them.",

    "home.matmul.kicker": "Interactive",
    "home.matmul.title": "Matrix multiplication",
    "home.matmul.desc": "See a product as composition: do B, then A. Watch why order matters and why determinants multiply.",

    "matmul.title": "Multiplying = composing",
    "matmul.sub": "A matrix product is a <em>composition</em>: AB means \"do B first, then A\". Order matters, so AB is usually not BA. See <a href=\"glossary.html#matrix\">matrix</a> &amp; <a href=\"glossary.html#determinant\">determinant</a>.",
    "matmul.stageHint": "Apply B first, then A. The grid carries the result of B into A.",
    "matmul.stageHintBA": "Apply A first, then B. The grid carries the result of A into B.",
    "matmul.matrixA": "Matrix A (applied second)",
    "matmul.matrixB": "Matrix B (applied first)",
    "matmul.animate": "Animate composition",
    "matmul.showBA": "Show B∘A instead",
    "matmul.showAB": "Show A∘B instead",
    "matmul.applyingB": "Stage 1: applying B",
    "matmul.thenA": "Stage 2: then A",
    "matmul.applyingA": "Stage 1: applying A",
    "matmul.thenB": "Stage 2: then B",
    "matmul.product": "Product AB",
    "matmul.productBA": "Product BA",
    "matmul.detA": "det(A)",
    "matmul.detB": "det(B)",
    "matmul.detProductOf": "det(A) · det(B)",
    "matmul.detProduct": "det(AB)",
    "matmul.detProductBA": "det(BA)",
    "matmul.hint": "Notice det(AB) = det(A) · det(B), always. Swapping the order changes the product matrix (AB ≠ BA) but never its determinant, since det(AB) = det(BA). The shaded patch is the image of the unit square; see <a href=\"glossary.html#determinant\">determinant</a>.",
    "matmul.p.rotShear": "A: rotate 90°, B: shear x",
    "matmul.p.scaleRot": "A: scale 2×, B: rotate 45°",
    "matmul.p.shearShear": "A: shear x, B: shear y",
    "matmul.p.flipRot": "A: flip y, B: rotate 90°",

    "matmul3d.p.rotShear": "A: rotate z 90°, B: shear z→x",
    "matmul3d.p.scaleRot": "A: scale 1.5×, B: rotate y 45°",
    "matmul3d.p.reflectRot": "A: reflect z, B: rotate z 90°",
    "matmul3d.hint": "Notice det(AB) = det(A) · det(B), always. Swapping the order changes the product matrix (AB ≠ BA) but never its determinant, since det(AB) = det(BA). The shaded box is the image of the unit cube; see <a href=\"glossary.html#determinant\">determinant</a>.",
  };
})();
