/* UI chrome strings — Español. A complete overlay (proves the i18n plumbing).
   Any missing key falls back to English automatically (see LA.t in shared.js). */
(function () {
  var S = (window.LA_STRINGS = window.LA_STRINGS || {});
  S.es = {
    "site.brand": "Álgebra lineal, visual",
    "site.footer": "Notas visuales de álgebra lineal, hechas con HTML, Canvas2D y KaTeX.",

    "nav.home": "Inicio",
    "nav.2d": "2D",
    "nav.3d": "3D",
    "nav.glossary": "Glosario",
    "nav.notation": "Notación",
    "nav.notes": "Notas",
    "nav.theme": "Cambiar tema claro u oscuro",
    "nav.language": "Idioma",

    "glossary.title": "Glosario",
    "glossary.intro": "Definiciones enlazadas. Cada término cita dónde se desarrolla en dos textos de referencia, y un vídeo cuando lo explica bien. Busca o filtra por etiqueta.",
    "glossary.search": "Buscar términos, símbolos, definiciones…",
    "glossary.allTags": "Todas",
    "glossary.formal": "Formal",
    "glossary.seeAlso": "Véase también",
    "glossary.sources": "Fuentes",
    "glossary.count": "{n} de {total} términos",
    "glossary.none": "Ningún término coincide.",
    "glossary.copyLink": "Copiar enlace a este término",

    "notation.title": "Notación y convenciones",
    "notation.intro": "Cada símbolo usado en estas notas, cómo leerlo y las convenciones que adopta este sitio.",
    "notation.colSymbol": "Símbolo",
    "notation.colName": "Nombre",
    "notation.colMeaning": "Significado",
    "notation.colRead": "Se lee",

    "notes.title": "Notas",
    "notes.intro": "Notas más extensas. Pasa el cursor sobre un término subrayado para ver su definición.",
    "notes.loading": "Cargando…",
    "notes.missing": "Nota no encontrada.",
    "notes.index": "Todas las notas",
    "notes.serveHint": "Las notas se cargan en tiempo de ejecución, así que esta página debe servirse por http(s) (GitHub Pages o un servidor local), no abrirse como file://.",

    "cite.free": "gratis",
    "cite.openAccess": "acceso abierto, PDF gratuito",
    "cite.paid": "de pago",
    "cite.video": "vídeo",

    "home.eyebrow": "Notas visuales",
    "home.title": "Álgebra lineal que puedes ver",
    "home.lede": "Notas visuales y duraderas de álgebra lineal: lo que buscas cuando olvidaste qué <em>significa</em> un determinante, no solo cómo calcularlo. Las definiciones y la notación son la columna; las visualizaciones interactivas cuelgan de ellas. Cada definición cita dos textos de referencia y, cuando lo explica mejor, un vídeo.",
    "home.2d.kicker": "Interactivo",
    "home.2d.title": "Transformaciones 2D",
    "home.2d.desc": "Escribe una matriz 2×2 y mira cómo se dobla la malla. El área del cuadrado unidad sombreado es el determinante.",
    "home.3d.kicker": "Interactivo",
    "home.3d.title": "Transformaciones 3D",
    "home.3d.desc": "Orbita una transformación 3×3. El volumen con signo del cubo unidad es el determinante.",
    "home.glossary.kicker": "Referencia",
    "home.glossary.title": "Glosario",
    "home.glossary.desc": "Definiciones enlazadas y citadas. Busca o filtra por etiqueta; sigue las fichas de 'véase también' entre ideas.",
    "home.notation.kicker": "Referencia",
    "home.notation.title": "Notación",
    "home.notation.desc": "Cada símbolo usado aquí, cómo leerlo y las convenciones que adopta este sitio.",
    "home.notes.kicker": "Notas",
    "home.notes.title": "Notas",
    "home.notes.desc": "Notas extensas con definiciones emergentes en cualquier término subrayado.",

    "viz.presets": "Preajustes",
    "viz.readout": "Lectura",
    "viz.animate": "Animar desde la identidad",
    "viz.reset": "Reiniciar",
    "viz.det": "Determinante",
    "viz.orient": "Orientación",
    "viz.orient.preserved": "conservada",
    "viz.orient.flipped": "invertida",
    "viz.orient.collapsed": "colapsada (singular)",
    "viz.iGoesTo": "î va a",
    "viz.jGoesTo": "ĵ va a",
    "viz.kGoesTo": "k̂ va a",

    "viz2d.title": "Matriz de transformación",
    "viz2d.sub": "Cada <em>columna</em> dice dónde aterriza un vector de la base. La malla se dobla para seguirla. Véase <a href=\"glossary.html#matrix\">matriz</a> y <a href=\"glossary.html#determinant\">determinante</a>.",
    "viz2d.iLands": "î aterriza aquí",
    "viz2d.jLands": "ĵ aterriza aquí",
    "viz2d.areaScale": "Escala de área",
    "viz2d.hint": "La región sombreada es la imagen del cuadrado unidad. Su área con signo es el <a href=\"glossary.html#determinant\">determinante</a>: negativo significa que el espacio se invirtió, y cero que colapsó sobre una recta y la matriz es <a href=\"glossary.html#singular\">singular</a>.",
    "viz2d.stageHint": "Cada columna de la matriz es donde aterriza un vector de la base.",
    "viz2d.p.rot90": "Rotar 90°",
    "viz2d.p.rot45": "Rotar 45°",
    "viz2d.p.shearX": "Cizalla x",
    "viz2d.p.shearY": "Cizalla y",
    "viz2d.p.scale2": "Escalar 2×",
    "viz2d.p.flipX": "Reflejar x",
    "viz2d.p.flipY": "Reflejar y",
    "viz2d.p.collapse": "Colapsar",

    "viz3d.title": "Transformación 3×3",
    "viz3d.sub": "Cada <em>columna</em> es donde aterriza un vector de la base. El <a href=\"glossary.html#determinant\">determinante</a> es ahora un <a href=\"glossary.html#area-volume\">volumen</a> con signo.",
    "viz3d.volScale": "Escala de volumen",
    "viz3d.hint": "La caja sombreada es la imagen del cubo unidad; su volumen con signo es el determinante. Volumen cero significa que el espacio se aplastó (<a href=\"glossary.html#singular\">singular</a>). Negativo significa que la lateralidad se invirtió.",
    "viz3d.stageHint": "Arrastra para orbitar · rueda para acercar",
    "viz3d.p.rotZ90": "Rotar z 90°",
    "viz3d.p.rotY45": "Rotar y 45°",
    "viz3d.p.shearZX": "Cizalla (z→x)",
    "viz3d.p.scale15": "Escalar 1.5×",
    "viz3d.p.reflectZ": "Reflejar z",
    "viz3d.p.squash": "Aplastar al plano",
  };
})();
