/* UI chrome strings - Español. A complete overlay (proves the i18n plumbing).
   Any missing key falls back to English automatically (see LA.t in shared.js). */
(function () {
  var S = (window.LA_STRINGS = window.LA_STRINGS || {});
  S.es = {
    "site.brand": "Álgebra lineal, visual",
    "site.footer": "Notas visuales de álgebra lineal, hechas con HTML, Canvas2D y KaTeX.",

    "nav.home": "Inicio",
    "nav.2d": "2D",
    "nav.3d": "3D",
    "nav.glossary": "Glosario",
    "nav.notation": "Notación",
    "nav.notes": "Notas",
    "nav.theme": "Cambiar tema claro u oscuro",
    "nav.language": "Idioma",

    "glossary.title": "Glosario",
    "glossary.intro": "Definiciones enlazadas. Cada término cita dónde se desarrolla en dos textos de referencia, y un vídeo cuando lo explica bien. Busca o filtra por etiqueta.",
    "glossary.search": "Buscar términos, símbolos, definiciones…",
    "glossary.allTags": "Todas",
    "glossary.formal": "Formal",
    "glossary.seeAlso": "Véase también",
    "glossary.sources": "Fuentes",
    "glossary.count": "{n} de {total} términos",
    "glossary.none": "Ningún término coincide.",
    "glossary.copyLink": "Copiar enlace a este término",

    "notation.title": "Notación y convenciones",
    "notation.intro": "Cada símbolo usado en estas notas, cómo leerlo y las convenciones que adopta este sitio.",
    "notation.colSymbol": "Símbolo",
    "notation.colName": "Nombre",
    "notation.colMeaning": "Significado",
    "notation.colRead": "Se lee",

    "notes.title": "Notas",
    "notes.intro": "Notas más extensas. Pasa el cursor sobre un término subrayado para ver su definición.",
    "notes.loading": "Cargando…",
    "notes.missing": "Nota no encontrada.",
    "notes.index": "Todas las notas",
    "notes.serveHint": "Las notas se cargan en tiempo de ejecución, así que esta página debe servirse por http(s) (GitHub Pages o un servidor local), no abrirse como file://.",

    "cite.free": "gratis",
    "cite.openAccess": "acceso abierto, PDF gratuito",
    "cite.paid": "de pago",
    "cite.video": "vídeo",

    "home.eyebrow": "Notas visuales",
    "home.title": "Álgebra lineal que puedes ver",
    "home.lede": "Notas visuales y duraderas de álgebra lineal: lo que buscas cuando olvidaste qué <em>significa</em> un determinante, no solo cómo calcularlo. Las definiciones y la notación son la columna; las visualizaciones interactivas cuelgan de ellas. Cada definición cita dos textos de referencia y, cuando lo explica mejor, un vídeo.",
    "home.2d.kicker": "Interactivo",
    "home.2d.title": "Transformaciones 2D",
    "home.2d.desc": "Escribe una matriz 2×2 y mira cómo se dobla la malla. El área del cuadrado unidad sombreado es el determinante.",
    "home.3d.kicker": "Interactivo",
    "home.3d.title": "Transformaciones 3D",
    "home.3d.desc": "Orbita una transformación 3×3. El volumen con signo del cubo unidad es el determinante.",
    "home.glossary.kicker": "Referencia",
    "home.glossary.title": "Glosario",
    "home.glossary.desc": "Definiciones enlazadas y citadas. Busca o filtra por etiqueta; sigue las fichas de 'véase también' entre ideas.",
    "home.notation.kicker": "Referencia",
    "home.notation.title": "Notación",
    "home.notation.desc": "Cada símbolo usado aquí, cómo leerlo y las convenciones que adopta este sitio.",
    "home.notes.kicker": "Notas",
    "home.notes.title": "Notas",
    "home.notes.desc": "Notas extensas con definiciones emergentes en cualquier término subrayado.",

    "viz.tab.transform": "Transformar",
    "viz.tab.inverse": "Inversa",
    "viz.tab.compose": "Componer",
    "viz.inv.sub": "La inversa A⁻¹ deshace A. Aplica A, luego A⁻¹, y el espacio vuelve a donde empezó.",
    "viz.inv.applyUndo": "Aplicar A y deshacer",
    "viz.inv.label": "Inversa A⁻¹",
    "viz.inv.none": "det(A) = 0, así que A colapsa el espacio a una dimensión menor. No hay inversa: un colapso no se puede deshacer.",
    "viz.inv.stageApply": "Aplicando A",
    "viz.inv.stageUndo": "Deshaciendo con A⁻¹",
    "viz.shapes.label": "Coloca una figura (arrástrala por el espacio)",
    "viz.shapes.clear": "Borrar figuras",
    "viz.inv.title": "La inversa deshace A",
    "viz.inv.matrixA": "Matriz A",
    "viz.shapes.point": "Colocar un punto",
    "viz.shapes.vector": "Colocar un vector",
    "viz.shapes.square": "Colocar un cuadrado unidad",
    "viz.shapes.circle": "Colocar un círculo",
    "viz.shapes.triangle": "Colocar un triángulo",
    "viz.shapes.fglyph": "Colocar una letra F",

    "viz.presets": "Preajustes",
    "viz.readout": "Lectura",
    "viz.animate": "Animar desde la identidad",
    "viz.reset": "Reiniciar",
    "viz.det": "Determinante",
    "viz.orient": "Orientación",
    "viz.orient.preserved": "conservada",
    "viz.orient.flipped": "invertida",
    "viz.orient.collapsed": "colapsada (singular)",
    "viz.iGoesTo": "î va a",
    "viz.jGoesTo": "ĵ va a",
    "viz.kGoesTo": "k̂ va a",

    "viz2d.title": "Matriz de transformación",
    "viz2d.sub": "Cada <em>columna</em> dice dónde aterriza un vector de la base. La malla se dobla para seguirla. Véase <a href=\"glossary.html#matrix\">matriz</a> &amp; <a href=\"glossary.html#determinant\">determinante</a>.",
    "viz2d.iLands": "î aterriza aquí",
    "viz2d.jLands": "ĵ aterriza aquí",
    "viz2d.areaScale": "Escala de área",
    "viz2d.hint": "La región sombreada es la imagen del cuadrado unidad. Su área con signo es el <a href=\"glossary.html#determinant\">determinante</a>: negativo significa que el espacio se invirtió, y cero que colapsó sobre una recta y la matriz es <a href=\"glossary.html#singular\">singular</a>.",
    "viz2d.stageHint": "Cada columna de la matriz es donde aterriza un vector de la base.",
    "viz2d.p.rot90": "Rotar 90°",
    "viz2d.p.rot45": "Rotar 45°",
    "viz2d.p.shearX": "Cizalla x",
    "viz2d.p.shearY": "Cizalla y",
    "viz2d.p.scale2": "Escalar 2×",
    "viz2d.p.flipX": "Reflejar x",
    "viz2d.p.flipY": "Reflejar y",
    "viz2d.p.collapse": "Colapsar",

    "viz3d.title": "Transformación 3×3",
    "viz3d.sub": "Cada <em>columna</em> es donde aterriza un vector de la base. El <a href=\"glossary.html#determinant\">determinante</a> es ahora un <a href=\"glossary.html#area-volume\">volumen</a> con signo.",
    "viz3d.volScale": "Escala de volumen",
    "viz3d.hint": "La caja sombreada es la imagen del cubo unidad; su volumen con signo es el determinante. Volumen cero significa que el espacio se aplastó (<a href=\"glossary.html#singular\">singular</a>). Negativo significa que la quiralidad se invirtió.",
    "viz3d.stageHint": "Arrastra para orbitar · rueda para acercar",
    "viz3d.p.rotZ90": "Rotar z 90°",
    "viz3d.p.rotY45": "Rotar y 45°",
    "viz3d.p.shearZX": "Cizalla (z→x)",
    "viz3d.p.scale15": "Escalar 1.5×",
    "viz3d.p.reflectZ": "Reflejar z",
    "viz3d.p.squash": "Aplastar al plano",

    "nav.matmul": "Multiplicar",
    "nav.concepts": "Conceptos",
    "keyideas.label": "Ideas clave para recordar",
    "glossary.theorems": "Teoremas",

    "concepts.title": "Conceptos",
    "concepts.intro": "Explicaciones visuales de las ideas en las que se apoyan las transformaciones. Cada una es interactiva y citada.",
    "concepts.kicker": "Concepto",
    "concepts.span.title": "Espacio generado",
    "concepts.span.desc": "Arrastra vectores y observa qué generan: una recta, un plano o todo el espacio, y el momento en que se vuelven dependientes.",
    "concepts.subspaces.title": "Rango, espacio columna y núcleo",
    "concepts.subspaces.desc": "Mira qué sobrevive a una aplicación y qué colapsa: espacio columna, núcleo, rango, y por qué det = 0 significa singular.",
    "concepts.dimensions.title": "Aplicaciones entre dimensiones",
    "concepts.dimensions.desc": "Las matrices no cuadradas llevan el espacio n-dimensional a m dimensiones. Mira cómo el 3D se aplasta a un plano, o el plano se eleva al espacio.",
    "concepts.dot.title": "Producto escalar",
    "concepts.dot.desc": "Arrastra dos vectores para ver el producto escalar como longitud por longitud por el coseno del ángulo entre ellos.",

    "home.matmul.kicker": "Interactivo",
    "home.matmul.title": "Multiplicación de matrices",
    "home.matmul.desc": "Ve un producto como composición: haz B, luego A. Observa por qué importa el orden y por qué se multiplican los determinantes.",

    "matmul.title": "Multiplicar = componer",
    "matmul.sub": "Un producto de matrices es una <em>composición</em>: AB significa \"haz B primero, luego A\". El orden importa, así que AB normalmente no es BA. Véase <a href=\"glossary.html#matrix\">matriz</a> &amp; <a href=\"glossary.html#determinant\">determinante</a>.",
    "matmul.stageHint": "Aplica B primero, luego A. La malla lleva el resultado de B a A.",
    "matmul.stageHintBA": "Aplica A primero, luego B. La malla lleva el resultado de A a B.",
    "matmul.matrixA": "Matriz A (aplicada en segundo lugar)",
    "matmul.matrixB": "Matriz B (aplicada primero)",
    "matmul.animate": "Animar composición",
    "matmul.showBA": "Mostrar B∘A en su lugar",
    "matmul.showAB": "Mostrar A∘B en su lugar",
    "matmul.applyingB": "Etapa 1: aplicando B",
    "matmul.thenA": "Etapa 2: luego A",
    "matmul.applyingA": "Etapa 1: aplicando A",
    "matmul.thenB": "Etapa 2: luego B",
    "matmul.product": "Producto AB",
    "matmul.productBA": "Producto BA",
    "matmul.detA": "det(A)",
    "matmul.detB": "det(B)",
    "matmul.detProductOf": "det(A) · det(B)",
    "matmul.detProduct": "det(AB)",
    "matmul.detProductBA": "det(BA)",
    "matmul.hint": "Observa que det(AB) = det(A) · det(B), siempre. Cambiar el orden cambia la matriz producto (AB ≠ BA) pero nunca su determinante, ya que det(AB) = det(BA). La región sombreada es la imagen del cuadrado unidad; véase <a href=\"glossary.html#determinant\">determinante</a>.",
    "matmul.p.rotShear": "A: rotar 90°, B: cizalla x",
    "matmul.p.scaleRot": "A: escalar 2×, B: rotar 45°",
    "matmul.p.shearShear": "A: cizalla x, B: cizalla y",
    "matmul.p.flipRot": "A: reflejar y, B: rotar 90°",

    "matmul3d.p.rotShear": "A: rotar z 90°, B: cizalla z→x",
    "matmul3d.p.scaleRot": "A: escalar 1.5×, B: rotar y 45°",
    "matmul3d.p.reflectRot": "A: reflejar z, B: rotar z 90°",
    "matmul3d.hint": "Observa que det(AB) = det(A) · det(B), siempre. Cambiar el orden cambia la matriz producto (AB ≠ BA) pero nunca su determinante, ya que det(AB) = det(BA). La caja sombreada es la imagen del cubo unidad; véase <a href=\"glossary.html#determinant\">determinante</a>.",

    "dot.title": "El producto escalar",
    "dot.sub": "El producto escalar <em>u · v</em> mide cuánto apunta un vector en la dirección del otro. Arrastra las puntas. Véase <a href=\"glossary.html#dot-product\">producto escalar</a>.",
    "dot.stageHint": "Arrastra la punta de cualquiera de las flechas. Observa la proyección de u sobre v.",
    "dot.vecU": "vector u",
    "dot.vecV": "vector v",
    "dot.swap": "Proyectar v sobre u en su lugar",
    "dot.swapBack": "Proyectar u sobre v en su lugar",
    "dot.p.aligned": "Alineados",
    "dot.p.perp": "Perpendiculares",
    "dot.p.opposed": "Opuestos",
    "dot.p.oblique": "Oblicuos",
    "dot.normU": "‖u‖",
    "dot.normV": "‖v‖",
    "dot.angle": "ángulo θ",
    "dot.projUonV": "proyección de u sobre v",
    "dot.projVonU": "proyección de v sobre u",
    "dot.dot": "u · v",
    "dot.perpFlag": "u · v = 0: los vectores son perpendiculares. Ninguno apunta en la dirección del otro en absoluto.",
    "dot.signAcute": "El ángulo es agudo, así que u · v es positivo: u se inclina en el mismo sentido que v.",
    "dot.signObtuse": "El ángulo es obtuso, así que u · v es negativo: u se inclina en contra de v.",
    "dot.signZeroVec": "Un vector tiene longitud cero, así que u · v es 0 y el ángulo no está definido.",
    "dot.geomLabel": "El significado geométrico",
    "dot.geomBody": "Traza una perpendicular desde la punta de u hasta la recta que pasa por v. La longitud con signo de esa sombra es <em>‖u‖ cos θ</em>. Multiplícala por <em>‖v‖</em> y obtienes el producto escalar: <em>u · v = ‖u‖‖v‖ cos θ</em>. Es positivo cuando el ángulo es agudo, cero cuando los vectores son perpendiculares y negativo cuando el ángulo es obtuso.",
    "dot.dualityNote": "Siguiendo el \"Dot products and duality\" de 3Blue1Brown: calcular u · v es lo mismo que aplicar el vector fila <em>uᵀ</em>, una matriz 1×2 que lleva el plano a la recta numérica, a v. El producto escalar esconde una aplicación lineal.",

    "sub.title": "Espacio columna, núcleo y rango",
    "sub.sub": "Una matriz <em>A</em> lleva entradas a salidas. El <em>espacio columna</em> es todo lo que puede alcanzar; el <em>núcleo</em> es todo lo que aplasta a cero. Véase <a href=\"glossary.html#singular\">singular</a> &amp; <a href=\"glossary.html#determinant\">determinante</a>.",
    "sub.stageHint": "Las columnas generan el espacio columna. El núcleo es lo que se aplasta a cero.",
    "sub.key.col1": "columna 1",
    "sub.key.col2": "columna 2",
    "sub.key.null": "núcleo",
    "sub.rank": "Rango",
    "sub.colspace": "Espacio columna",
    "sub.nullspace": "Núcleo",
    "sub.invertible": "Invertible",
    "sub.col.plane": "un plano (todo ℝ²)",
    "sub.col.line": "una recta",
    "sub.col.point": "el origen",
    "sub.null.zero": "solo el origen {0}",
    "sub.null.line": "una recta",
    "sub.null.plane": "todo el plano",
    "sub.inv.yes": "sí, rango completo",
    "sub.inv.no": "no, singular",
    "sub.chain.full": "det ≠ 0, así que rango = 2, el núcleo es solo {0}, y A es invertible.",
    "sub.chain.singular": "det = 0, así que rango < 2, el núcleo es más que {0}, y A no es invertible.",
    "sub.hint": "La cadena es un mismo enunciado de cuatro formas: <strong>det = 0 &nbsp;&hArr;&nbsp; rango &lt; 2 &nbsp;&hArr;&nbsp; el núcleo es más que {0} &nbsp;&hArr;&nbsp; no invertible</strong>. Véase <a href=\"glossary.html#singular\">singular</a>.",
    "sub.keyidea.label": "Idea clave",
    "sub.keyidea.body": "Cuando det = 0 las columnas son dependientes, así que el espacio de salida colapsa y pierde una dimensión. El núcleo es exactamente lo que se aplasta a cero: un colapso mayor significa un núcleo mayor.",
    "sub.cite.prefix": "Basado en",
    "sub.p.fullRank": "Rango completo",
    "sub.p.rank1": "Rango 1 (singular)",
    "sub.p.zero": "Matriz cero",

    "span.title": "Espacio generado por dos vectores",
    "span.sub": "El <em>espacio generado</em> por u y v es cada punto que puedes alcanzar como combinación a·u + b·v. Dos flechas independientes alcanzan todo el plano; dos paralelas alcanzan solo una recta. Véase <a href=\"glossary.html#span\">espacio generado</a> &amp; <a href=\"glossary.html#linear-independence\">independencia lineal</a>.",
    "span.stageHint": "Arrastra la punta de cualquiera de las flechas. El espacio generado es todo lo que puedes alcanzar con a·u + b·v.",
    "span.canvasAria": "Dos vectores u y v dibujados como flechas desde el origen en el plano. Arrastra cualquiera de las puntas. El espacio generado por los dos vectores se muestra en vivo: todo el plano cuando son independientes, una recta por el origen cuando son paralelos, o solo el origen cuando ambos son cero.",
    "span.vecU": "vector u",
    "span.vecV": "vector v",
    "span.keyIdea": "Idea clave: el espacio generado es todo lo que dos flechas pueden construir estirando y sumando. La dimensión es cuántas direcciones independientes tienes realmente.",
    "span.p.independent": "Independientes (plano)",
    "span.p.parallel": "Paralelos (recta)",
    "span.p.point": "Colapso (punto)",
    "span.uIs": "u",
    "span.vIs": "v",
    "span.independent": "Linealmente independientes",
    "span.dim": "dim(span)",
    "span.spanIs": "Espacio generado",
    "span.spanPlane": "todo R²",
    "span.spanLine": "una recta por el origen",
    "span.spanPoint": "solo el origen",
    "span.hintPlane": "Dos vectores independientes alcanzan cada punto del plano, así que el espacio generado es bidimensional.",
    "span.hintLine": "Los dos vectores son paralelos, así que toda combinación se queda en una recta por el origen. El espacio generado es unidimensional.",
    "span.hintPoint": "Ambos vectores son cero, así que el único punto que puedes alcanzar es el origen. El espacio generado es de dimensión cero.",
    "span.yes": "sí",
    "span.no": "no",
    "span.targetLabel": "Expresa un punto",
    "span.targetSub": "Haz clic en cualquier lugar de la malla para colocar un punto objetivo y verlo escrito como a·u + b·v cuando es alcanzable.",
    "span.targetPoint": "Objetivo",
    "span.combo": "a·u + b·v",
    "span.clearTarget": "Borrar objetivo",
    "span.unreachable": "fuera del espacio generado",
    "span.reachableNotUnique": "en el espacio generado (coeficientes no únicos)",

    "dim.title": "Aplicaciones no cuadradas entre dimensiones",
    "dim.sub": "Una matriz no cuadrada <em>m×n</em> es una aplicación lineal de una entrada <em>n</em>-dimensional a una salida <em>m</em>-dimensional. Sus <em>n</em> columnas son a dónde van a parar los <em>n</em> vectores de la base de entrada, que ahora viven en la salida. Véase <a href=\"glossary.html#matrix\">matriz</a> &amp; <a href=\"glossary.html#rank\">rango</a>.",
    "dim.stageHint": "Cada columna es a dónde aterriza un vector de la base de entrada.",
    "dim.tag.input": "Entrada",
    "dim.tag.output": "Salida",
    "dim.aria.in": "Espacio de entrada: los vectores de la base del dominio.",
    "dim.aria.out": "Espacio de salida: a dónde aterriza cada vector de la base de entrada, las columnas de la matriz.",
    "dim.case.23": "2×3",
    "dim.case.32": "3×2",
    "dim.case.12": "1×2",
    "dim.case.23.aria": "matriz 2 por 3, lleva R3 a R2",
    "dim.case.32.aria": "matriz 3 por 2, lleva R2 a R3",
    "dim.case.12.aria": "matriz 1 por 2, lleva R2 a la recta numérica",
    "dim.matrixLabel": "La matriz",
    "dim.cellAria": "fila {r}, columna {c}",
    "dim.lands": "{v} aterriza aquí",
    "dim.maps": "lleva",
    "dim.rank": "rango",
    "dim.image": "imagen",
    "dim.img.point": "un único punto (el origen)",
    "dim.img.line": "una recta por el origen",
    "dim.img.plane2": "todo el plano",
    "dim.img.plane3": "un plano por el origen en el espacio",
    "dim.img.numberline": "toda la recta numérica",
    "dim.note.squash": "Más entradas que salidas, así que algunas direcciones se aplastan: la aplicación tiene un núcleo no trivial.",
    "dim.note.embed": "Menos entradas que salidas, así que la entrada se incrusta como una lámina plana que no puede llenar el espacio mayor.",
    "dim.keyidea": "<strong>Idea clave.</strong> Las columnas son las imágenes de los vectores de la base de entrada. Leer a dónde van î, ĵ (y k̂) en el espacio de salida te dice toda la aplicación.",
    "dim.cite": "3Blue1Brown: Nonsquare matrices as transformations between dimensions ↗",
    "dim.p.dropZ": "Quitar z",
    "dim.p.project": "Proyectar",
    "dim.p.collapseLine": "Colapsar a una recta",
    "dim.p.skew": "Sesgar",
    "dim.p.embedXY": "Incrustar plano xy",
    "dim.p.tilt": "Inclinar",
    "dim.p.slant": "Ladear",
    "dim.p.lineIn3": "Colapsar a una recta",
    "dim.p.readX": "Leer x",
    "dim.p.sum": "Suma x+y",
    "dim.p.diff": "Diferencia x−y",
    "dim.p.zero": "Aplicación cero",
  };
})();
